version: '2.0'
services:
  api:
    restart: always
    env_file:
      - api.env
    build:
      context: .
      args:
        ARCH: library # will pick up the user's system arch with manifests
    ports:
      - 8080:8080
    links:
      - postgres
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "moedersvoormoeders"
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - apiWorkdir:/opt/mvm-api/
  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    ports:
      - 8081:8080
volumes:
  postgresdb: {}
  apiWorkdir: {}
