version: '2.0'
services:
  api:
    build: .
    ports:
      - 8080:8080
    links:
      - postgres
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "moedersvoormoeders"
    volumes:
      - postgresdb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    ports:
      - 8081:8080
volumes:
  postgresdb: {}
