name: Docker Image Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armhf, arm64v8]
    steps:
      - uses: actions/checkout@v1
      - name: Get qemu-user-static
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Configure Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register
      - name: Build the Docker image
        run: |
          if [[ "${{ matrix.arch }}" == "amd64" ]]; then export QEMU_BIN="qemu-x86_64-static"; fi
          if [[ "${{ matrix.arch }}" == "armhf" ]]; then export QEMU_BIN="qemu-arm-static"; fi
          if [[ "${{ matrix.arch }}" == "arm64v8" ]]; then export QEMU_BIN="qemu-aarch64-static"; fi
          cp /usr/bin/$QEMU_BIN ./
          docker build . --build-arg="ARCH=${{ matrix.arch }}" --build-arg="QEMU_BIN=$QEMU_BIN" --file Dockerfile --tag moedersvoormoeders/api:${{ matrix.arch }}-$GITHUB_SHA
      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "meyskens" --password-stdin
      - name: Push image
        run: docker push  moedersvoormoeders/api:${{ matrix.arch }}-$GITHUB_SHA
  publish-manifest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Log in to registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "meyskens" --password-stdinn
      - name: Create Manifest
        run: |
          docker manifest create $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:amd64-$GITHUB_SHA $DOCKER_PREFIX:armhf-$GITHUB_SHA $DOCKER_PREFIX:arm64v8-$GITHUB_SHA
          docker manifest annotate $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:amd64-$GITHUB_SHA --arch amd64
          docker manifest annotate $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:armhf-$GITHUB_SHA --arch arm --variant v7
          docker manifest annotate $DOCKER_PREFIX:$GITHUB_SHA $DOCKER_PREFIX:arm64v8-$GITHUB_SHA --arch arm64 --variant armv8
          docker manifest push $DOCKER_PREFIX:$GITHUB_SHA
        env:
          DOCKER_PREFIX: moedersvoormoeders/api